Feat10/test setup
d-lama/d-lama-service pull request #13
Opened 2023-04-05 16:10 UTC by joelgrand

Working on #10:
* defines a test project (Test) using MSTest-framework
* first unit tests created
* first integration tests created

2023-04-06 09:08 UTC, guentgia requested changes
Great job Gioelo! Thank you very much. The test environment with MS test looks good. As we just discussed, please have a look at the comments for requested changes.

2023-04-08 10:42 UTC, joelgrand commented on D-lama-service/Test/IntegrationTests/UserControllerTest.cs
> +            // # 1. Invalid request object.
done now

2023-04-08 10:42 UTC, joelgrand commented on D-lama-service/Test/IntegrationTests/UserControllerTest.cs
> +namespace MSTest.IntegrationTests
renamed them

2023-04-08 10:43 UTC, joelgrand commented on D-lama-service/Test/IntegrationTests/UserControllerTest.cs
> +
done as well

2023-04-10 17:52 UTC, guentgia reviewed
Thank you @joelgrand ! Looks great.

2023-04-10 17:53 UTC, guentgia approved these changes

2023-04-10 17:53 UTC, merged